/** Auto-generated from editor_glyph_pack.json — run: node scripts/generate-glyph-fonts.mjs */
const FONT_MAP: Record<string, string> = {
  "NotoMusic": "'Noto Music', sans-serif",
  "NotoSans": "'Noto Sans', sans-serif",
  "NotoSansAdlam": "'Noto Sans Adlam', 'Noto Sans', sans-serif",
  "NotoSansAnatolianHieroglyphs": "'Noto Sans Anatolian Hieroglyphs', 'Noto Sans', sans-serif",
  "NotoSansArabic": "'Noto Sans Arabic', 'Noto Sans', sans-serif",
  "NotoSansArmenian": "'Noto Sans Armenian', 'Noto Sans', sans-serif",
  "NotoSansAvestan": "'Noto Sans Avestan', 'Noto Sans', sans-serif",
  "NotoSansBalinese": "'Noto Sans Balinese', 'Noto Sans', sans-serif",
  "NotoSansBamum": "'Noto Sans Bamum', 'Noto Sans', sans-serif",
  "NotoSansBassaVah": "'Noto Sans Bassa Vah', 'Noto Sans', sans-serif",
  "NotoSansBatak": "'Noto Sans Batak', 'Noto Sans', sans-serif",
  "NotoSansBengali": "'Noto Sans Bengali', 'Noto Sans', sans-serif",
  "NotoSansBhaiksuki": "'Noto Sans Bhaiksuki', 'Noto Sans', sans-serif",
  "NotoSansBrahmi": "'Noto Sans Brahmi', 'Noto Sans', sans-serif",
  "NotoSansBuginese": "'Noto Sans Buginese', 'Noto Sans', sans-serif",
  "NotoSansBuhid": "'Noto Sans Buhid', 'Noto Sans', sans-serif",
  "NotoSansCJKsc": "'Noto Sans SC', 'Noto Sans', sans-serif",
  "NotoSansCanadianAboriginal": "'Noto Sans Canadian Aboriginal', 'Noto Sans', sans-serif",
  "NotoSansCarian": "'Noto Sans Carian', 'Noto Sans', sans-serif",
  "NotoSansChakma": "'Noto Sans Chakma', 'Noto Sans', sans-serif",
  "NotoSansCham": "'Noto Sans Cham', 'Noto Sans', sans-serif",
  "NotoSansCherokee": "'Noto Sans Cherokee', 'Noto Sans', sans-serif",
  "NotoSansCoptic": "'Noto Sans Coptic', 'Noto Sans', sans-serif",
  "NotoSansDeseret": "'Noto Sans Deseret', 'Noto Sans', sans-serif",
  "NotoSansDevanagari": "'Noto Sans Devanagari', 'Noto Sans', sans-serif",
  "NotoSansDuployan": "'Noto Sans Duployan', 'Noto Sans', sans-serif",
  "NotoSansEgyptianHieroglyphs": "'Noto Sans Egyptian Hieroglyphs', 'Noto Sans', sans-serif",
  "NotoSansElbasan": "'Noto Sans Elbasan', 'Noto Sans', sans-serif",
  "NotoSansEthiopic": "'Noto Sans Ethiopic', 'Noto Sans', sans-serif",
  "NotoSansGeorgian": "'Noto Sans Georgian', 'Noto Sans', sans-serif",
  "NotoSansGlagolitic": "'Noto Sans Glagolitic', 'Noto Sans', sans-serif",
  "NotoSansGujarati": "'Noto Sans Gujarati', 'Noto Sans', sans-serif",
  "NotoSansGurmukhi": "'Noto Sans Gurmukhi', 'Noto Sans', sans-serif",
  "NotoSansHanunoo": "'Noto Sans Hanunoo', 'Noto Sans', sans-serif",
  "NotoSansHebrew": "'Noto Sans Hebrew', 'Noto Sans', sans-serif",
  "NotoSansImperialAramaic": "'Noto Sans Imperial Aramaic', 'Noto Sans', sans-serif",
  "NotoSansInscriptionalPahlavi": "'Noto Sans Inscriptional Pahlavi', 'Noto Sans', sans-serif",
  "NotoSansInscriptionalParthian": "'Noto Sans Inscriptional Parthian', 'Noto Sans', sans-serif",
  "NotoSansJP": "'Noto Sans JP', 'Noto Sans', sans-serif",
  "NotoSansJavanese": "'Noto Sans Javanese', 'Noto Sans', sans-serif",
  "NotoSansKR": "'Noto Sans KR', 'Noto Sans', sans-serif",
  "NotoSansKannada": "'Noto Sans Kannada', 'Noto Sans', sans-serif",
  "NotoSansKharoshthi": "'Noto Sans Kharoshthi', 'Noto Sans', sans-serif",
  "NotoSansKhmer": "'Noto Sans Khmer', 'Noto Sans', sans-serif",
  "NotoSansLao": "'Noto Sans Lao', 'Noto Sans', sans-serif",
  "NotoSansLepcha": "'Noto Sans Lepcha', 'Noto Sans', sans-serif",
  "NotoSansLimbu": "'Noto Sans Limbu', 'Noto Sans', sans-serif",
  "NotoSansLinearA": "'Noto Sans Linear A', 'Noto Sans', sans-serif",
  "NotoSansLinearB": "'Noto Sans Linear B', 'Noto Sans', sans-serif",
  "NotoSansLisu": "'Noto Sans Lisu', 'Noto Sans', sans-serif",
  "NotoSansLydian": "'Noto Sans Lydian', 'Noto Sans', sans-serif",
  "NotoSansMahajani": "'Noto Sans Mahajani', 'Noto Sans', sans-serif",
  "NotoSansMalayalam": "'Noto Sans Malayalam', 'Noto Sans', sans-serif",
  "NotoSansMandaic": "'Noto Sans Mandaic', 'Noto Sans', sans-serif",
  "NotoSansMath": "'Noto Sans Math', 'Noto Sans', sans-serif",
  "NotoSansMedefaidrin": "'Noto Sans Medefaidrin', 'Noto Sans', sans-serif",
  "NotoSansMeeteiMayek": "'Noto Sans Meetei Mayek', 'Noto Sans', sans-serif",
  "NotoSansMendeKikakui": "'Noto Sans Mende Kikakui', 'Noto Sans', sans-serif",
  "NotoSansMeroitic": "'Noto Sans Meroitic', 'Noto Sans', sans-serif",
  "NotoSansMiao": "'Noto Sans Miao', 'Noto Sans', sans-serif",
  "NotoSansModi": "'Noto Sans Modi', 'Noto Sans', sans-serif",
  "NotoSansMongolian": "'Noto Sans Mongolian', 'Noto Sans', sans-serif",
  "NotoSansMultani": "'Noto Sans Multani', 'Noto Sans', sans-serif",
  "NotoSansMyanmar": "'Noto Sans Myanmar', 'Noto Sans', sans-serif",
  "NotoSansNKo": "'Noto Sans N Ko', 'Noto Sans', sans-serif",
  "NotoSansNewTaiLue": "'Noto Sans New Tai Lue', 'Noto Sans', sans-serif",
  "NotoSansOgham": "'Noto Sans Ogham', 'Noto Sans', sans-serif",
  "NotoSansOlChiki": "'Noto Sans Ol Chiki', 'Noto Sans', sans-serif",
  "NotoSansOldItalic": "'Noto Sans Old Italic', 'Noto Sans', sans-serif",
  "NotoSansOldSouthArabian": "'Noto Sans Old South Arabian', 'Noto Sans', sans-serif",
  "NotoSansOldTurkic": "'Noto Sans Old Turkic', 'Noto Sans', sans-serif",
  "NotoSansOriya": "'Noto Sans Oriya', 'Noto Sans', sans-serif",
  "NotoSansOsmanya": "'Noto Sans Osmanya', 'Noto Sans', sans-serif",
  "NotoSansPhagsPa": "'Noto Sans Phags Pa', 'Noto Sans', sans-serif",
  "NotoSansPhoenician": "'Noto Sans Phoenician', 'Noto Sans', sans-serif",
  "NotoSansRunic": "'Noto Sans Runic', 'Noto Sans', sans-serif",
  "NotoSansSamaritan": "'Noto Sans Samaritan', 'Noto Sans', sans-serif",
  "NotoSansSaurashtra": "'Noto Sans Saurashtra', 'Noto Sans', sans-serif",
  "NotoSansShavian": "'Noto Sans Shavian', 'Noto Sans', sans-serif",
  "NotoSansSinhala": "'Noto Sans Sinhala', 'Noto Sans', sans-serif",
  "NotoSansSylotiNagri": "'Noto Sans Syloti Nagri', 'Noto Sans', sans-serif",
  "NotoSansSymbols": "'Noto Sans Symbols 2', sans-serif",
  "NotoSansSymbols2": "'Noto Sans Symbols 2', sans-serif",
  "NotoSansSyriac": "'Noto Sans Syriac', 'Noto Sans', sans-serif",
  "NotoSansTagalog": "'Noto Sans Tagalog', 'Noto Sans', sans-serif",
  "NotoSansTagbanwa": "'Noto Sans Tagbanwa', 'Noto Sans', sans-serif",
  "NotoSansTaiLe": "'Noto Sans Tai Le', 'Noto Sans', sans-serif",
  "NotoSansTaiTham": "'Noto Sans Tai Tham', 'Noto Sans', sans-serif",
  "NotoSansTaiViet": "'Noto Sans Tai Viet', 'Noto Sans', sans-serif",
  "NotoSansTamil": "'Noto Sans Tamil', 'Noto Sans', sans-serif",
  "NotoSansTelugu": "'Noto Sans Telugu', 'Noto Sans', sans-serif",
  "NotoSansThaana": "'Noto Sans Thaana', 'Noto Sans', sans-serif",
  "NotoSansThai": "'Noto Sans Thai', 'Noto Sans', sans-serif",
  "NotoSansTifinagh": "'Noto Sans Tifinagh', 'Noto Sans', sans-serif",
  "NotoSansVai": "'Noto Sans Vai', 'Noto Sans', sans-serif",
  "NotoSansYi": "'Noto Sans Yi', 'Noto Sans', sans-serif",
  "NotoSerifTibetan": "'Noto Serif Tibetan', 'Noto Serif', serif",
  "custom_scan_lines": "var(--font-kao)",
  "editor_space": "inherit",
};

export function getFontFamily(fontUsed: string): string {
  const key = fontUsed.replace(/-Regular$/, '');
  return FONT_MAP[key] ?? 'var(--font-kao)';
}
